# Generated by Django 3.2.18 on 2023-02-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('tier_1', 'Can view 3 suggestions'), ('tier_2', 'Can view 6 suggestions'))},
        ),
    ]
