# Generated by Django 3.2.18 on 2023-02-26 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': (('Basic', 'Can view 3 suggestions'), ('tier_2', 'Can view 6 suggestions'), ('enterprise', 'can get binary image'))},
        ),
    ]
